#ifndef GMABI_H
#define GMABI_H

#define GM_API_VERSION 2U
#define GM_ARCH_X86_64 1U
#define GM_ARCH_AARCH64 2U
#define GM_ARCH_RISCV64 3U
#define GM_PROGRAM_BASE 0x0000000040000000ULL
#define GM_PROGRAM_IMAGE_MAX 65536ULL
#define GM_PROGRAM_HEADER_SIZE 24U
#define GM_STORE_BLOCK 1024U
#define GM_UDP_MAX 1024U
#define GM_IMAGE_MAGIC 0x31304d47U

#define GM_SVC_EXIT 0U
#define GM_SVC_WRITE 1U
#define GM_SVC_PRINT_U64 2U
#define GM_SVC_TICKS 3U
#define GM_SVC_GATEWAY 4U
#define GM_SVC_PING 5U
#define GM_SVC_STORE_READ 6U
#define GM_SVC_STORE_WRITE 7U
#define GM_SVC_STORE_APPEND 8U
#define GM_SVC_RESOURCE_ACQUIRE 9U
#define GM_SVC_RESOURCE_RELEASE 10U
#define GM_SVC_STORE_STAT 11U
#define GM_SVC_UDP_EXCHANGE 12U

#define GM_RESOURCE_TCP 1U
#define GM_RESOURCE_UDP 2U

#endif
